### ISSUE TITLE
Remarks on "onAdminAfterSave" and "$config['enabled']"

### ISSUE THREAD

**Issue by pamtbaau** [wernerjoss/grav-plugin-caldav2ics#2]
- `onAdminAfterSave` and `$config = $this->config()`
The name `onAdminAfterSave` may cause some confusion. Although the data has been saved to disk, the variable `$config` does NOT reflect the newly saved data, but instead still reflects the previous state.

  To get the newly saved data, you need to reference `$event['object']`, which contains the data being submitted by the user.
  ```
  /** @var Data */
  $data = $event['object'];   <-- Contains the new data submitted by Admin
  $isEnabled = $data['enabled'];
  $hasJobsEnabled = $data['scheduled_jobs']['enabled'];
  ```

- $config['enabled'] is quite useless. 
If the plugin is not enabled, `function getSubscribedEvents()` will not be called and hence your events will not be enabled and $config['enabled'] will never be evaluated. On the other hand, if the plugin is enabled, $config['enabled'] will always be 'true'.

- To skip processing of `onAdminAfterSaved` on every submit of Admin you could do:
  ```
  /** @var Uri */
  $uri = $this->grav['uri'];

  if ('caldav2ics' !== $uri->basename()) {
       return;
  }
  ```

**Comment by wernerjoss** [comment]
>     * `onAdminAfterSave` and `$config = $this->config()`
>       The name `onAdminAfterSave` may cause some confusion. Although the data has been saved to disk, the variable `$config` does NOT reflect the newly saved data, but instead still reflects the previous state.

ok, so this confusion hit me :smile:  - I really expected this to reflect the new data...

>       To get the newly saved data, you need to reference `$event['object']`, which contains the data being submitted by the user.
>       ```
>       /** @var Data */
>       $data = $event['object'];   <-- Contains the new data submitted by Admin
>       $isEnabled = $data['enabled'];
>       $hasJobsEnabled = $data['scheduled_jobs']['enabled'];
>       ```

done.

>     * $config['enabled'] is quite useless.
>       If the plugin is not enabled, `function getSubscribedEvents()` will not be called and hence your events will not be enabled and $config['enabled'] will never be evaluated. On the other hand, if the plugin is enabled, $config['enabled'] will always be 'true'.
> 

ok, omitted that check.

>     * To skip processing of `onAdminAfterSaved` on every submit of Admin you could do:
>       ```
>       /** @var Uri */
>       $uri = $this->grav['uri'];
>       
>       if ('caldav2ics' !== $uri->basename()) {
>            return;
>       }
>       ```

I added this to onPluginsInitialized() and checked that onAdminAfterSave() is only called when saving the plugin configuration page, not on any other submit in Admin.

**Comment by pamtbaau** [comment]
```
/** @var config **/
$config = $e['object'];   //  <-- Contains the new data submitted by Admin, do NOT use '$config = $this->config();' here !
```

Two remarks on this... 
- `/** @var config **/` tells the IDE of which type the following variable is. It is not `config`, but `Data`. 
- Using variable name `$config` here is misleading. Elsewhere variable `$config` refers to `$this->config()` which is of type `Config`. However, here it is the data submitted by Admin, which is of type `Data`. I would prefer to use a more meaningful name.

As a side note: Do you use the debugger? If so, why all these `dump()` lines?

**Comment by wernerjoss** [comment]
> ```
> /** @var config **/
> $config = $e['object'];   //  <-- Contains the new data submitted by Admin, do NOT use '$config = $this->config();' here !
> ```
> 
> Two remarks on this...
> 
>     * `/** @var config **/` tells the IDE of which type the following variable is. It is not `config`, but `Data`.
> 
>     * Using variable name `$config` here is misleading. Elsewhere variable `$config` refers to `$this->config()` which is of type `Config`. However, here it is the data submitted by Admin, which is of type `Data`. I would prefer to use a more meaningful name.

I have changed this now to $cfgdata, should be more clear.

> As a side note: Do you use the debugger? If so, why all these `dump()` lines?

yes, I use the clockwork browser extension.
I know I could then use
`$this->grav['debugger']->addMessage($cfgdata);`
to see the value in the message tab of the debug bar, but a simple dump() is sometimes easier.
for a public release, the dump's will be removed.

**Comment by pamtbaau** [comment]
Sorry, I meant the php code debugger with which you step through the code line by line and watch the content of variables.

I think I've mentioned it before (yes I know, I'm nagging...), but the preferred code style for variables used by Grav and [Symfony](https://symfony.com/doc/current/contributing/code/standards.htm) is camelCase: `$configData`. It makes it more pleasing to the eyes for other code readers when same styling is being used...

**Comment by wernerjoss** [comment]
> Sorry, I meant the php code debugger with which you step through the code line by line and watch the content of variables.

so, you mean something like xdebug, right ?
no.
 
> I think I've mentioned it before (yes I know, I'm nagging...), but the preferred code style for variables used by Grav and [Symfony](https://symfony.com/doc/current/contributing/code/standards.htm) is camelCase: `$configData`. It makes it more pleasing to the eyes for other code readers when same styling is being used...

fixed :-)

**Comment by pamtbaau** [comment]
You should really consider using Xdebug to improve the quality of your code...

**Comment by wernerjoss** [comment]
I'm using the official [docker-grav](https://github.com/getgrav/docker-grav) for plugin development.
this does not contain Xdebug.
I'll see if I can get it in there...
