### ISSUE TITLE
Support download access without login

### ISSUE THREAD

**Issue by xf-** [wernerjoss/grav-plugin-caldav2ics#3]
Nextcloud supports share URL, and it outputs ICS file without any requirement for authentication.

**Comment by wernerjoss** [comment]
well, then you don't need this plugin at all.
just use use your favourite ics calendar directly with the shared ics URL.

**Comment by xf-** [comment]
OK, thx. I tried it, to use the URL, and it didn't work for me. I thought, maybe only files in data/calendar would work

**Comment by wernerjoss** [comment]
you mean, you tried the nextcloud .ics URL with [this plugin](https://github.com/wernerjoss/grav-plugin-fullcalendar) and it didn't work ?
if so, did you use the correct page template (calendar) for your calendar page ?
